### ISSUE TITLE
How to configure a jail

### ISSUE THREAD

**Issue by mset** [robertdebock/ansible-role-fail2ban#7]
Hi,

Could you please point me in the right direction as to how to configure a jail (ssh for example) using this role?

Thanks!

**Comment by robertdebock** [comment]
All details are in the [README.md](https://github.com/robertdebock/ansible-role-fail2ban#role-variables)

Just to be sure, you can't create a jail with this role...

**Comment by mset** [comment]
So this role is about installing f2b and configuring the root aspects of it but not configuring jails, if I understand it correctly.
As it is, fail2ban won't even start on a system that has this role installed as it does not have any jail configuration.
What would be the best way to set up jails when using this role?

**Comment by rohankrishnadev** [comment]
> Hi,
> 
> Could you please point me in the right direction as to how to configure a jail (ssh for example) using this role?
> 
> Thanks!

I've got a very basic ssh jail configured using the following:

**fail2banvars.yml**
```yaml
---
fail2ban_jail_configuration:
  - option: enabled
    value: "yes"
    section: sshd
  - option: mode
    value: "aggressive"
    section: sshd
  - option: port
    value: "ssh"
    section: sshd
  - option: logpath
    value: "%(sshd_log)s"
    section: sshd
  - option: backend
    value: "%(sshd_backend)s"
    section: sshd
```

It does get a bit cumbersome if you're trying to get multiple jails setup. Might be easier to just copy a jail.local file with pre-configured jails.
