### ISSUE TITLE
Check mode don't work

### ISSUE THREAD

**Issue by yodatak** [robertdebock/ansible-role-fail2ban#8]
Hi when i use my playbook to install your role thje check mode failed on this task , it could be cool to make it work in check mode to be sure to what changes will be made

TASK [robertdebock.fail2ban : test if fail2ban_jail_configuration is set correctly] *******************************************************************************************************************************************************************************************************************************************
fatal: [192.168.1.X]: FAILED! => {}

MSG:

The conditional check 'item.value | length > 0' failed. The error was: Unexpected templating type error occurred on ({% if item.value | length > 0 %} True {% else %} False {% endif %}): object of type 'bool' has no len()

**Comment by robertdebock** [comment]
Hi, that's unexpected, you are seeing `tasks/assert.yml` fail because something in the `fail2ban_jail_configuration` is set to `yes` or `no`. I don't see how that relates to check_mode, it should also fail in regular mode.

I can reproduce this issue using this `fail2ban_jail_configuration`:

```yaml
fail2ban_jail_configuration:
  - option: ignoreself
    value: true
    section: DEFAULT
```

In the example above the value `true` should be quoted to prevent Ansible from making a boolean out of it. This would work:

```yaml
fail2ban_jail_configuration:
  - option: ignoreself
    value: "true"
    section: DEFAULT
```

If you continue to struggle, can you show me the variables you're feeding this role so I can analyse further?

Regards,

Robert de Bock.
